
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { AuthContextProvider } from "@/context/AuthContext";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <GoogleOAuthProvider clientId="742176195552-snfusug219agik0m9mbd002190tq567v.apps.googleusercontent.com">
          <AuthContextProvider >
        {children}
        </AuthContextProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
